spring:
  application:
    name: whc-eureke-server-ha
---
spring:
     profiles: peer1            #指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer:8762/eureka/  #将自己注册到peer2这个Eureka上面去
---
spring:
     profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer:8761/eureka/  #将自己注册到peer1这个Eureka上面去
