server:
  port: 8020

spring:
  application:
    name: whc-customer-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true   #表示将自己的ip注册到Eureka Server上，若不配置或设置成false，表示提下哦那个的hostname到Server上
feign:
  hystrix:
    enabled: true
# 说明：请务必注意，从Spring Cloud Dalston开始，Feign默认是不开启Hystrix的。
# 因此，如使用Dalston请务必额外设置属性：feign.hystrix.enabled=true，否则断路器不会生效。
# 而，Spring Cloud Angel/Brixton/Camden中，Feign默认都是开启Hystrix的。无需设置该属性。